### ISSUE TITLE
[BUG] Logrotate doesn't run since change to busybox cron

### ISSUE THREAD

**Issue by pagdot** [linuxserver/docker-baseimage-alpine#222]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

logrotate just never runs (since the changes to cron). From what I've found out, it seems like in busybox cron periodic tasks in `/etc/periodic` aren't implemented -> these are just ignored. Probably something like <https://github.com/linuxserver/fanart-nginx/blob/8945d091bfa0318c5f4dc509c022992a8d2256aa/root/etc/crontabs/root#L4> should be able to fix the issue.

Discord support thread: <https://discord.com/channels/354974912613449730/1188173818070573138>

### Expected Behavior

logrotate should be called daily

### Steps To Reproduce

use an nginx based container. wait until your fs is full of uncompressed logs

### Environment

```markdown
- OS: Ubuntu 22.04
- How docker service was installed: According to official docker docs (NOT snap)
```

### Docker creation

```bash
doesn't matter
```

### Container logs

```bash
none regarding this issue
```

**Comment by aptalca** [comment]
Periodic tasks are included in the default crontab that ships with alpine

**Comment by nemchik** [comment]
I'm working on this. We don't ship the default root crontab with swag, thus logrotate (via daily periodic) is not triggered.

The fix will be specifically in the swag repo, and a few others.

**Comment by nemchik** [comment]
This issue is specific to swag, and a few other images where we ship a `root` crontab without the periodic run parts. It will be fixed in https://github.com/linuxserver/docker-swag/pull/441 (and other respective PRs for affected images). I'm going to close this for now as there is no need for any changes in the alpine base or nginx base.
