### ISSUE TITLE
GUID of abc group

### ISSUE THREAD

**Issue by JOduMonT** [linuxserver/docker-baseimage-alpine#27]
#### It's not a real issue; it's more a suggestion about a little detail who's bugging me.

but before proposing a PR
I see two ways of doing it

### 1. we could replace the [line 35](https://github.com/linuxserver/docker-baseimage-alpine/blob/master/Dockerfile#L35)
```
groupadd -g 911 abc
useradd -g 911 -u 911 -d /config -s /bin/false abc
```
so the group abc have the same id of the user abc `GID == UID`

### 2. we omit the group by replacing the [line 35](https://github.com/linuxserver/docker-baseimage-alpine/blob/master/Dockerfile#L35) with :
```
useradd -g users -u 911 -N -d /config -s /bin/false abc
```

**Comment by sparklyballs** [comment]
why ?

**Comment by JOduMonT** [comment]
nevermind;

it's a lot translation between docker to lxc

actually this is have 0 effect because the GUID is redefine by the script 10-adduser
