### ISSUE TITLE
exec format error on armv7

### ISSUE THREAD

**Issue by trasba** [linuxserver/docker-baseimage-alpine#48]
------------------------------

## Expected Behavior
container should start up

## Current Behavior
`standard_init_linux.go:211: exec user process caused "exec format error"`

## Steps to Reproduce
`docker run -it --rm --name test lsiobase/alpine`
leads to the error
`docker run -it --rm --name test lsiobase/alpine:arm32v7-3.8`
works
So I believe the arch is detected falsely. As I understand that alpine without tag is an multiarch image?

## Environment
**OS:**      Raspbian
**cat /etc/*-release output:**
```
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```
**CPU architecture:** armv7
**uname -a output:**
`Linux kapi3 4.19.57-v7+ #1244 SMP Thu Jul 4 18:45:25 BST 2019 armv7l GNU/Linux`
**Docker version:**
```
Client: Docker Engine - Community
 Version:           19.03.1
 API version:       1.40
 Go version:        go1.12.5
 Git commit:        74b1e89
 Built:             Thu Jul 25 21:33:17 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.1
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.5
  Git commit:       74b1e89
  Built:            Thu Jul 25 21:27:09 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.6
  GitCommit:        894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc:
  Version:          1.0.0-rc8
  GitCommit:        425e105d5a03fabd737a126ad93d62a9eeede87f
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```
Hope this helps.
If not let me know.

**Comment by trasba** [comment]
OK I see it, there is an old latest tagged image existing that does not support multiarch. And it is old anyhow.
Maybe that could be removed

**Comment by aptalca** [comment]
With the baseimages, use the version tags, not latest
`lsiobase/alpine:3.10`
`lsiobase/ubuntu:bionic`
