### ISSUE TITLE
abc-user member of several groups (IDs) in the container

### ISSUE THREAD

**Issue by tapufd** [linuxserver/docker-baseimage-alpine#56]
See discussion first on your discourse:
https://discourse.linuxserver.io/t/abc-user-member-of-several-groups-ids-in-the-container/2024/3

What I finally need is to have the abc-user member of several groups (IDs) in the container.
For example PGID=1001;1002;1003
The first one 1001 would be used as GID, but the others 1002 1003 would then be extra groups the abc-user is member of.
By this I can decide in detail what the user abc has rights to…
Or have an extra variable besides PGID by which I can define the extra group memberships of the abc-user.

I think the file in question that actually does the work is:
https://github.com/linuxserver/docker-baseimage-alpine/blob/master/root/etc/cont-init.d/10-adduser

I was asked to continue the discussion here...
/T

**Comment by aptalca** [comment]
That's the file that handles the uid/pid of user abc. If you want to add it to multiple groups, the easiest solution is to create a custom script via [this](https://blog.linuxserver.io/2019/09/14/customizing-our-containers/) and have it add abc to whichever group you like with usermod -aG

**Comment by tapufd** [comment]
This solution is exactly what I wanted/needed!
Works great!
Many thx for the quick support!
/T

**Comment by tapufd** [comment]
As stated: solution works great!
