### ISSUE TITLE
system time broken on arm32

### ISSUE THREAD

**Issue by mgrechukh** [linuxserver/docker-baseimage-alpine#71]
$ docker run -d --name baseimage-alpine ghcr.io/linuxserver/baseimage-alpine:arm32v7-3.13 
$ docker exec -it baseimage-alpine date
Thu Jan  1 00:00:00 UTC 1970

$ uname -a

Linux raspberrypi 5.4.51-v7l+ #1333 SMP Mon Aug 10 16:51:40 BST 2020 armv7l GNU/Linux

$ docker info 2>&1 | grep Archite
 Architecture: armv7l

$ date
Sun Apr 11 18:10:22 CEST 2021

## Expected Behavior

System time match to provided from host.

## Current Behavior

exactly zero epoch.

## Steps to Reproduce
1. Run any application container based on this one (amongst these are baseimage-nginx, therefore Grocy and so on)
2. Check unixtime inside container

## Environment
**OS:** Linux (both 5.10.17-v8+ and 5.4.51-v7l+ builds were checked)

**CPU architecture:** arm32

**Docker**: docker-ce from official repository, both 20.10.5 and 19.03.12 versions had been tested
 
## Command used to create docker container (run/create/compose/screenshot)

docker run -d --name baseimage-alpine ghcr.io/linuxserver/baseimage-alpine:arm32v7-3.13 

## Docker logs
$ docker logs baseimage-alpine
 docker logs baseimage-alpine
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 
usermod: no changes

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    911
User gid:    911
-------------------------------------

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

Your DockerHost is most likely running an outdated version of libseccomp

To fix this, please visit https://docs.linuxserver.io/faq#libseccomp

Some apps might not behave correctly without this

@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.

**Comment by Roxedus** [comment]
Do you want to follow the issue template and post full logs?

**Comment by mgrechukh** [comment]
> Do you want to follow the issue template and post full logs?

Updated with container logs as defined by template. Is it ok now?

**Comment by Roxedus** [comment]
> Is it ok now?

A full log has our logo

**Comment by mgrechukh** [comment]
> > Is it ok now?
> 
> A full log has our logo

Updated.

**Comment by Roxedus** [comment]
Thanks, the message I was expected popped up, you need to patch your host. docs.linuxserver.io/faq#libseccomp
