### ISSUE TITLE
MIRROR env is not working

### ISSUE THREAD

**Issue by Diluka** [linuxserver/docker-baseimage-alpine#91]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I want to override this env to change apk repo
https://github.com/linuxserver/docker-baseimage-alpine/blob/master/Dockerfile#L8

using mirror

## Current Behavior

not using

## Steps to Reproduce

```docker-compose.yml
services:
  nginx:
    image: linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - URL=xxxxxx
      - MIRROR=https://mirrors.aliyun.com/alpine
      - DOCKER_MODS=linuxserver/mods:swag-auto-reload
    volumes:
      - ./nginx/config:/config
    ports:
      - 80:80
      - 443:443
    restart: always
```

## Environment
**OS:** ubuntu 22
**CPU architecture:** x86_64
**How docker service was installed:** via `get.docker.com`

## Command used to create docker container (run/create/compose/screenshot)

`docker compose up -d`

## Docker logs

```log
[mod-init] Curl/JQ was not found on this system for Docker mods installing
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.14/community/x86_64/APKINDEX.tar.gz
```

**Comment by Roxedus** [comment]
Please fill the issue template
